quantize: use `std::abs()` instead of `abs()`
`abs()` accepts `int` but `o.val_i64` is `int64_t`. `std::abs()`
accepts not only `int` but also `int64_t`.

This fixes the following `-Wabsolute-value` warning by Clang:

    src/llama-quant.cpp:656:66: error: absolute value function 'abs' given an argument of type 'const int64_t' (aka 'const long') but has parameter of type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]
      656 |                 gguf_set_val_u32(ctx_out.get(), o.key, (uint32_t)abs(o.val_i64));
          |                                                                  ^
    src/llama-quant.cpp:656:66: note: use function 'std::abs' instead
      656 |                 gguf_set_val_u32(ctx_out.get(), o.key, (uint32_t)abs(o.val_i64));
          |                                                                  ^~~
          |                                                                  std::abs